name: Security Audit

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 1 * * *' # Runs every day at 01:00 UTC

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4' # Adjust to match your project's Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit
